apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-pod
spec:
  selector:
    matchLabels:
      app: mongo 
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: myapp
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom: 
            secretKeyRef: 
              name: mongodb-secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: mongodb-secret
              key: password      
 