apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoexp-pod
spec:
  selector:
    matchLabels:
      app: mongo-express 
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: myapp
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom: 
            secretKeyRef: 
              name: mongodb-secret
              key: username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom: 
            secretKeyRef: 
              name: mongodb-secret
              key: password      
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef: 
              name: mongoexp-config
              key: database_url